//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPruebaPSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int ventaId { get; set; }
        public int vehiculoId { get; set; }
        public string cedula { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public decimal precioTotal { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Vendedore Vendedore { get; set; }
    }
}
